# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62dbeed4220563ac5a87b1a0376d95aa9c32f66d91d39b70af6d418a96f5f70e19811fb9cae076315c4f3822f8021cda3d76ebee5574f2b7d7f0ea6159ed56a5

test:
  secret_key_base: 6217bec3eeb446ae6063e961f8e464b97f104bafe8a871b3b3a6ec96d1e2806c24bcd1cda98ae4745358bffac34079933b0174a63e40d8552ccb52e126d35421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
